### ISSUE TITLE
Issue about residual_block

### ISSUE THREAD

**Issue by MingtaoGuo** [DebeshJha/NanoNet#1]
Hi, 

Thank you for your great job. However, I have a question about the "residual block", as shown in follow, is it suppose to use x_init? 

https://github.com/DebeshJha/NanoNet/blob/7a7c9fef29e699a59b6be6afbb9e6a7b8f63553c/model.py#L25

Mingtao
Best regards

**Comment by reshalfahsi** [comment]
@MingtaoGuo see https://github.com/DebeshJha/NanoNet/pull/3
